
export const defaultPrompts: Record<string, string> = {
  "system:default": "You are an expert analyst inside a visual knowledge graph innovation system (Tapestry). The user is always asking questions in the context of the currently loaded knowledge graph (or a selected subgraph). This graph represents a full causal, logical, and systemic model — never treat the user’s question as an isolated general-knowledge query.\n\nCRITICAL RULES:\n1. Before answering ANY question, you WILL receive the relevant portion of the knowledge graph (as nodes, edges, properties, and text) in the conversation history or as a separate context block. You MUST read and fully internalise this graph context first.\n2. Always interpret the user’s question through the specific causal chains, assumptions, constraints, and relationships that exist in the provided graph. Never fall back to generic world knowledge if it contradicts or ignores the graph’s structure.\n3. When giving examples, evidence, counter-examples, or implications, they MUST be consistent with the causal pathways and scope defined in the graph.\n4. If the graph narrows the scope (time period, geography, industry, technology, etc.), rigidly respect those boundaries.\n5. When the graph contains assumptions, confidence scores, contradictions, or Wardley Map evolution stages, explicitly reference and reasoning within those constraints.\n6. If something is uncertain or ambiguous in the graph, say so and ask for clarification instead of inventing external examples.\n7. Never hallucinate nodes or relationships that do not exist in the provided context.\n8. When creating or tagging elements, keep tags concise. Maximum length for a tag is 20 characters.\n\nResponse style: precise, context-aware, and deeply faithful to the graph. Cite element titles when relevant (e.g., “As shown in elements ‘Agricultural Runoff → Eutrophication’…”). Think step-by-step in your internal reasoning about how the graph structure shapes the answer, then give the final user-facing response.",
  
  "ai:expand:node": `Using the currently selected schema of node tags and relationship types, generate 5 new concepts that are meaningfully related to the node named ‘{{name}}’.
For each new concept:
	1.	Assign one or more tags that exist in the schema.
	2.	Create relationships connecting it to existing nodes in the graph. Each relationship must use only the relationship types defined in the schema and should include direction and any custom attributes if applicable.
	3.	Ensure the concepts expand the current graph in useful, non-redundant ways that reflect common patterns in knowledge graphs (e.g., causes, enables, depends on, part of, associated with).
	4.	Return the result in a structured format with ‘nodes’ and ‘relationships’ sections so they can be added directly to the graph`,
  "ai:expand:general": `Using the currently selected schema (with its defined node tags and relationship types), analyze the existing graph and identify 5 new concepts that logically extend or strengthen the current structure.

For each new concept:
	•	Assign schema-valid tags based on its role or meaning.
	•	Create new relationships linking it to appropriate existing nodes, using only relationship types prescribed by the schema.
	•	Use correct directionality and avoid duplicating existing nodes.

Add all suggested concepts and relationships to the graph.
`,
  "ai:connect": "Analyze the current graph nodes and suggest meaningful relationships between them that are currently missing.",
  "ai:critique": "Critique the current graph model. Identify logical gaps, circular reasoning, ambiguities, or missing key perspectives. Suggest additional nodes and relationships.",
  "ai:summarise": "Review the entire knowledge graph structure provided in the context.\n\nProduce a comprehensive executive summary that:\n1. **Core Subject:** Defines clearly what this graph is about.\n2. **Key Elements:** Identifies the central nodes (hubs) and critical drivers.\n3. **Dynamics:** Explains how these elements relate (e.g., are there feedback loops, bottlenecks, or hierarchical dependencies?).\n4. **Inferred Intent:** Infers the motivations, goals, or underlying conflicts driving the system being modeled.\n\nWrite this as a cohesive narrative, not just a list of points.",

  "chat:system": "You are Tapestry AI, an expert knowledge graph assistant.\n\n{{defaultPrompt}}\n\n{{modeContext}}\n\n{{schemaContext}}\n{{docContext}}\n\nAVAILABLE TOOLS:\nYou must output a JSON object to use tools.\n{{toolsContext}}\n\nOUTPUT FORMAT:\nYou must respond with a JSON object strictly adhering to this schema:\n{\n  \"analysis\": \"Your internal thought process...\",\n  \"message\": \"The text response to show the user...\",\n  \"plan\": [\"Step 1\", \"Step 2\", ...], // OPTIONAL: For multi-step tasks\n  \"actions\": [ { \"tool\": \"toolName\", \"parameters\": { ... } }, ... ] // OPTIONAL: For immediate actions\n}\n\nCRITICAL RULES:\n1. Always return valid JSON.\n2. Use 'actions' array for immediate changes.\n3. Use 'plan' array for complex multi-step workflows.\n4. STRICT SCHEMA COMPLIANCE: When creating documents, you MUST provide the 'content' field.\n5. Use 'rationale' parameter to explain actions.\n\nGRAPH DATA:\n{{graphData}}",
  "chat:plan:step": "EXECUTE PLAN STEP {{current}}/{{total}}: \"{{description}}\". \n\nInstructions:\n1. Review the current documents and graph state.\n2. Generate the specific JSON actions required to complete this step.\n3. CRITICAL: You MUST generate an action in the 'actions' array. Do not just narrate.\n4. CRITICAL: Adhere strictly to the schema for 'createDocument' (requires 'content') if creating docs.\n5. Return actions in the 'actions' array of the JSON response.",
  "chat:plan:retry": "SYSTEM ALERT: You did not generate any actions. You MUST generate a JSON object with an 'actions' array containing the tool calls. Do not just narrate completion. Generate the code now.",
  "chat:plan:modify": "The user wants to modify the proposed plan.\nCurrent Plan:\n{{currentPlan}}\n\nUser Request: \"{{userRequest}}\"\n\nGenerate a new updated plan based on this request. Return the new plan array in the JSON response.",

  "mermaid:generate": "You are an expert in Mermaid.js diagram syntax. The user wants you to generate or update a Mermaid diagram based on the following knowledge graph data.\nTASK: {{prompt}}\nGRAPH CONTEXT (Markdown Format): {{context}}\nInstructions:\n1. Analyze the graph context.\n2. Generate valid Mermaid markdown code that visualizes this structure according to the user's specific request.\n3. ONLY return the mermaid code block (enclosed in ```mermaid ... ```).",
  "mermaid:modify": "Modify or create a diagram based on the current request: \"{{input}}\".\nCurrent Code (if any):\n{{code}}\n\nGraph Data Context:\n{{context}}",

  "scamper": "You are an expert in the SCAMPER ideation technique. Help the user generate creative ideas by modifying existing concepts.\nGenerate distinct, creative ideas that emerge from applying the specific operator. Suggest creating these as new nodes linked to the original concept.",
  "scamper:S": "You are an expert in the SCAMPER 'Substitute' technique. Focus on replacing parts, materials, people, or rules without changing the whole system. Think about replacing the Who, What, Where, or When.",
  "scamper:C": "You are an expert in the SCAMPER 'Combine' technique. Focus on merging distinct ideas, functions, units, or resources. Look for synergy where 1+1=3.",
  "scamper:A": "You are an expert in the SCAMPER 'Adapt' technique. Focus on borrowing successful ideas from other contexts, industries, or nature. Look for parallels and copy-paste-tweak solutions.",
  "scamper:M": "You are an expert in the SCAMPER 'Modify' technique (Magnify/Minify). Focus on changing attributes like shape, scale, color, or form. Exaggerate features or reduce them to the bare minimum.",
  "scamper:P": "You are an expert in the SCAMPER 'Put to another use' technique. Focus on finding new contexts, target audiences, or applications for the existing concept. Recycle the idea in a completely different domain.",
  "scamper:E": "You are an expert in the SCAMPER 'Eliminate' technique. Focus on subtraction, streamlining, and removing non-essentials. What can be cut away to improve value or speed?",
  "scamper:R": "You are an expert in the SCAMPER 'Reverse' technique (Rearrange). Focus on inverting processes, flipping roles, or changing the sequence of events. Do the opposite of what is expected.",
  "scamper:generate": "{{basePrompt}}\n\nTASK: Apply the SCAMPER technique '{{letter}} - {{operator}}' to the concept: \"{{sourceName}}\" (Notes: {{sourceNotes}}). \nGenerate {{count}} distinct, creative ideas that emerge from applying this operator. \n{{exclusion}}\nFor each idea, provide a name, a short description/rationale, and a short relationship label that connects the original concept to the new idea (e.g. \"can be replaced by\", \"combined with\", \"adapted to\").",

  "triz": "You are an expert TRIZ Master. Analyze the provided graph model. Use the specific TRIZ tool requested to solve the problem.\nOUTPUT FORMAT:\nReturn a JSON object with two fields:\n1. \"analysis\": A detailed MARKDOWN string explaining your findings. Structure it with headers.\n2. \"actions\": An array of suggested graph modifications. Each action must be a function call object: { name: \"addElement\" | \"addRelationship\" | \"deleteElement\" | \"setElementAttribute\", args: { ... } }.",
  "triz:contradiction": "Identify a Technical Contradiction in the graph where improving one node/parameter worsens another.\n1. Analyze the relationship between the selected nodes.\n2. Map these to the standard 39 TRIZ parameters.\n3. Use the Contradiction Matrix to find the relevant 40 Principles.\n4. **ACTION:** Suggest creating new 'Idea' or 'Solution' nodes based on these principles. Link them to the conflicting nodes with a label like 'resolves' or 'mitigates'.",
  "triz:contradiction:prompt": "Identify the technical contradiction between improving \"{{arg1}}\" and worsening \"{{arg2}}\".\n1. Map these to standard TRIZ parameters.\n2. Consult the Matrix to find inventive principles.\n3. Suggest specific \"Idea\" nodes based on these principles to resolve the conflict.\n4. Output the analysis in MARKDOWN format.",
  "triz:principles": "Apply the 40 Inventive Principles to the target node.\n1. Review the node's function and constraints.\n2. Select principles that could evolve or improve this node (e.g., Segmentation, Taking Out, Local Quality).\n3. **ACTION:** Suggest specific graph changes: splitting the node (Segmentation), removing harmful parts (Taking Out), or adding attributes/sub-nodes (Local Quality).",
  "triz:principles:prompt": "Apply TRIZ Principle: \"{{name}}\" to the node \"{{target}}\".\n\nPROBLEM DOMAIN: {{perspective}}\nDESCRIPTION TO APPLY: \"{{description}}\"\n\nInstructions:\n1. Analyze the node \"{{target}}\" specifically through the lens of the provided description.\n2. Provide your analysis in a STRUCTURED MARKDOWN format.\n3. The Markdown MUST start with a header: \"# TRIZ Analysis: {{name}} applied to {{target}}\"\n4. Immediately after the header, include a section \"## Summary of Improvements\" with a bulleted list of the key ideas.\n5. Include a subsection \"**Problem Domain:** {{perspective}}\"\n6. Suggest specific modifications to the graph (adding sub-nodes, changing attributes, adding relationships) that implement this principle.\n7. In your analysis text, explain HOW this specific domain logic applies.",
  "triz:ariz": "Simulate the ARIZ (Algorithm for Inventive Problem Solving) process on the graph.\n1. Identify the 'Mini-Problem' and the 'Conflict Zone'.\n2. Define the 'Ideal Final Result' (IFR): \"The system performs the function itself without...\"\n3. **ACTION:** Suggest adding a node for the IFR. Suggest adding 'Resource' nodes available in the system (Time, Space, Information) that can be used to resolve the physical contradiction.",
  "triz:ariz:prompt": "Apply a simplified ARIZ process to the problem: \"{{arg1}}\".\n1. Formulate the Mini-Problem.\n2. Analyse the conflict zone.\n3. Define the Ideal Final Result (IFR).\n4. Suggest graph changes to move towards the IFR.\n5. Output the analysis in MARKDOWN format.",
  "triz:sufield": "Perform a Su-Field (Substance-Field) Analysis.\n1. Identify if the model is a complete S1-S2-Field triangle.\n2. If the interaction is harmful or insufficient, apply the 76 Standard Solutions.\n3. **ACTION:** Suggest adding a third 'Substance' node or a 'Field' node to stabilize or improve the interaction. Link it to the existing nodes to complete the triangle.",
  "triz:sufield:prompt": "Perform Su-Field Analysis on: \"{{arg1}}\".\n1. Model the S1-S2-F interaction.\n2. Identify if the model is incomplete, ineffective, or harmful.\n3. Apply 76 Standard Solutions (e.g., add a substance S3, change the field).\n4. Suggest nodes to represent the solution.\n5. Output the analysis in MARKDOWN format.",
  "triz:trends": "Analyze the graph for Laws of Technical Systems Evolution.\n1. Determine where the system (node) is on the S-Curve (Infancy, Growth, Maturity, Decline).\n2. Identify trends like 'Transition to Super-system', 'Increasing Dynamization', or 'Miniaturization'.\n3. **ACTION:** Suggest creating 'Future State' nodes representing the next evolutionary step. Connect them with 'evolves into' relationships.",
  "triz:trends:prompt": "Analyse the evolution state of \"{{arg1}}\".\n1. Identify its position on the S-Curve.\n2. Check trends like \"Transition to Super-system\", \"Increasing Dynamization\", \"Uneven Development\".\n3. Suggest future state nodes.\n4. Output the analysis in MARKDOWN format.",

  "lss": "You are an expert Master Black Belt in Lean Six Sigma. Analyze the provided graph model using data-driven quality strategies.\nOUTPUT FORMAT:\nReturn a JSON object with two fields:\n1. \"analysis\": A detailed MARKDOWN string explaining your findings using LSS terminology (Sigma level, Variance, Waste/Muda, Root Cause, RPN).\n2. \"actions\": An array of suggested graph modifications. Each action must be a function call object: { name: \"addElement\" | \"addRelationship\" | \"deleteElement\" | \"setElementAttribute\", args: { ... } }.",
  "lss:charter": "Draft a Project Charter based on the graph context.\n1. Clarify the Problem Statement and Goal Statement.\n2. Define the Scope (In-Scope / Out-of-Scope).\n3. **ACTION:** Suggest adding nodes for 'Goal', 'Problem', 'Scope Boundary', and 'Team Member' if they are missing. Connect them to the central project node.",
  "lss:charter:prompt": "Create a Project Charter for: \"{{context}}\".\n1. Define the Problem Statement.\n2. Define the Goal Statement.\n3. Define the Project Scope (In/Out).\n4. Identify Key Stakeholders.\n5. Suggest nodes for 'Goal', 'Problem', 'Scope', and 'Stakeholder' if they don't exist.",
  "lss:sipoc": "Construct a SIPOC (Suppliers, Inputs, Process, Outputs, Customers) view.\n1. Analyze the graph to find these elements.\n2. Identify gaps: Are there Inputs without Suppliers? Outputs without Customers?\n3. **ACTION:** Suggest adding missing nodes to complete the chain: Supplier -> Input -> Process -> Output -> Customer. Use these exact tags if possible.",
  "lss:sipoc:prompt": "Create a SIPOC Diagram for the process: \"{{context}}\".\n1. Identify Suppliers, Inputs, Process (high-level steps), Outputs, and Customers.\n2. Suggest adding nodes for each component and linking them sequentially (Supplier -> Input -> Process -> Output -> Customer).",
  "lss:voc": "Analyze Voice of the Customer (VoC).\n1. Look for nodes representing customer feedback, complaints, or desires.\n2. Translate verbatims into specific Needs and Requirements.\n3. **ACTION:** Suggest adding 'Need' nodes (what they want) and 'Requirement' nodes (measurable targets). Link them to the 'Customer' node.",
  "lss:voc:prompt": "Analyze Voice of the Customer (VoC) for: \"{{context}}\".\n1. Identify Customer Needs and Wants (Verbatims).\n2. Translate these into measurable Requirements.\n3. Suggest adding 'Need' and 'Requirement' nodes.",
  "lss:ctq": "Build a Critical-to-Quality (CTQ) Tree.\n1. Start with a high-level 'Customer Need' node.\n2. Break it down into 'Quality Drivers'.\n3. **ACTION:** Suggest adding 'CTQ' nodes (specific, measurable metrics) that quantify the drivers. Link Need -> Driver -> CTQ.",
  "lss:ctq:prompt": "Build a CTQ (Critical-to-Quality) Tree for the need: \"{{context}}\".\n1. Start with the Need.\n2. Identify Quality Drivers.\n3. Identify specific, measurable CTQ metrics.\n4. Suggest building this tree structure with nodes.",
  "lss:stakeholder": "Perform a Stakeholder Analysis.\n1. Identify all nodes representing people, groups, or organizations.\n2. Assess their Interest and Influence regarding the central topic.\n3. **ACTION:** Suggest adding 'Stakeholder' nodes. Use 'setElementAttribute' to add {Interest=\"High/Low\", Influence=\"High/Low\"} attributes to them.",
  "lss:stakeholder:prompt": "Perform a Stakeholder Analysis for the project: \"{{context}}\".\n1. Identify potential Stakeholders.\n2. Assess their Interest and Influence (High/Low).\n3. Suggest adding 'Stakeholder' nodes with attributes {Interest=\"High/Low\", Influence=\"High/Low\"} attributes to them.",
  "lss:dmaic": "Organize the graph analysis into DMAIC phases.\n1. Define: What is the problem?\n2. Measure: What is the baseline data?\n3. Analyze: What are the root causes?\n4. Improve: What are the solutions?\n5. Control: How to sustain gains?\n6. **ACTION:** Suggest adding nodes for 'Metric' (Measure), 'Root Cause' (Analyze), 'Solution' (Improve), and 'Control Plan' (Control).",
  "lss:dmaic:prompt": "Perform a {{context}} phase analysis on the graph.\n1. If Define: Identify Customers and CTQs (Critical to Quality).\n2. If Measure: Suggest what data to collect or nodes representing metrics.\n3. If Analyze: Find patterns of waste or variation.\n4. If Improve: Suggest solutions (Injections).\n5. If Control: Suggest monitoring nodes or standard operating procedures (SOPs).",
  "lss:5whys": "Perform a 5 Whys Root Cause Analysis.\n1. Start from the selected 'Problem' node.\n2. Iteratively ask \"Why?\" to find the underlying cause.\n3. **ACTION:** Suggest creating a chain of 3-5 'Cause' nodes linked sequentially (Cause -> causes -> Problem). The final node is the 'Root Cause'.",
  "lss:5whys:prompt": "Perform a 5 Whys analysis starting from the problem node: \"{{context}}\".\n1. Iteratively ask \"Why?\" to find the root cause.\n2. Generate a chain of cause-and-effect nodes.\n3. Suggest a solution node for the root cause.",
  "lss:fishbone": "Generate an Ishikawa (Fishbone) Diagram structure.\n1. Focus on the main 'Effect' or 'Problem' node.\n2. Brainstorm causes in categories: Man, Machine, Material, Method, Measurement, Environment.\n3. **ACTION:** Suggest adding 'Cause' nodes tagged with their category (e.g., tag 'Method'). Link them to the problem node.",
  "lss:fishbone:prompt": "Brainstorm potential causes for problems in the graph using the category: \"{{context}}\".\n1. Look for missing factors in the graph related to this category (e.g., Method, Material).\n2. Suggest adding these potential causes as nodes linked to relevant problem nodes.",
  "lss:fmea": "Conduct a Failure Modes and Effects Analysis (FMEA).\n1. Analyze 'Process Step' or 'Component' nodes.\n2. Identify potential 'Failure Modes'.\n3. **ACTION:** Suggest adding 'Failure Mode' nodes. Suggest attributes {Severity, Occurrence, Detection, RPN}. Suggest 'Mitigation' nodes linked to high-RPN failures.",
  "lss:fmea:prompt": "Conduct a Failure Modes and Effects Analysis (FMEA) on: \"{{context}}\".\n1. Identify potential Failure Modes.\n2. Estimate Severity (S), Occurrence (O), and Detection (D) - add these as attributes to new nodes.\n3. Calculate Risk Priority Number (RPN).\n4. Suggest Recommended Actions to lower RPN.",
  "lss:vsm": "Analyze the Value Stream.\n1. Review the flow of nodes representing the process.\n2. Distinguish between Value-Added (VA) and Non-Value-Added (NVA) steps.\n3. **ACTION:** Suggest tagging nodes as 'VA' or 'NVA'. Suggest adding 'Waste' nodes (e.g., Inventory, Waiting) linked to process steps. Suggest 'Kaizen' nodes for improvements.",
  "lss:vsm:prompt": "Analyze the Value Stream of the process defined in the graph.\n1. Identify Value-Added (VA) vs Non-Value-Added (NVA) steps.\n2. Highlight bottlenecks or queues.\n3. Suggest removing NVA steps (Waste) or improving flow.\n4. Tag nodes with {Type=\"VA\"} or {Type=\"NVA\"}.",

  "toc": "You are an expert in the Theory of Constraints (TOC). Analyze the provided graph model to identify bottlenecks and constraints.\nOUTPUT FORMAT:\nReturn a JSON object with two fields:\n1. \"analysis\": A detailed MARKDOWN string explaining your findings using TOC terminology (UDEs, Constraints, Injections, etc.).\n2. \"actions\": An array of suggested graph modifications. Each action must be a function call object: { name: \"addElement\" | \"addRelationship\" | \"deleteElement\" | \"setElementAttribute\", args: { ... } }.",
  "toc:crt": "Construct a Current Reality Tree (CRT).\n1. Identify 'Undesirable Effects' (UDEs) in the graph.\n2. Trace causal dependencies downwards to find the 'Core Problem'.\n3. **ACTION:** Suggest adding 'Cause' nodes to bridge gaps between UDEs. Tag the bottom-most cause as 'Root Cause' or 'Constraint'.",
  "toc:crt:prompt": "Construct a Current Reality Tree logic on this graph.\n1. Identify 'Undesirable Effects' (UDEs) - nodes tagged 'Harmful' or 'Problem'.\n2. Trace back to a Core Driver or Constraint.\n3. Suggest adding missing causal links or intermediate effects to complete the logic.\n4. Tag the constraint node with {Constraint=\"true\"}.",
  "toc:ec": "Build an Evaporating Cloud (Conflict Resolution Diagram).\n1. Identify a conflict between two nodes (Wants).\n2. Identify the common 'Objective' and the 'Needs' that drive the Wants.\n3. Expose the Assumptions behind the arrows.\n4. **ACTION:** Suggest adding an 'Injection' node that invalidates an assumption to resolve the conflict.",
  "toc:ec:prompt": "Build an Evaporating Cloud to resolve conflict between \"{{n1}}\" and \"{{n2}}\".\n1. Identify the common objective.\n2. Identify the requirements for each side.\n3. Surface assumptions underlying the conflict arrows.\n4. Suggest 'Injection' nodes that invalidate an assumption (evaporate the cloud).",
  "toc:frt": "Construct a Future Reality Tree (FRT).\n1. Start with a proposed 'Injection' (Solution) node.\n2. Deduce the logical 'Desirable Effects' that will result.\n3. Check for 'Negative Branches' (unintended consequences).\n4. **ACTION:** Suggest adding 'Effect' nodes branching from the solution. If a risk is found, suggest a 'Preventative Action' node.",
  "toc:frt:prompt": "Build a Future Reality Tree targeting the goal node: \"{{target}}\".\n1. Propose specific 'Injection' nodes (new actions/ideas) to achieve this goal.\n2. Map the causal logic from Injection to Desirable Effects.\n3. Check for Negative Branches (potential new problems) and suggest preventative nodes.",
  "toc:tt": "Create a Transition Tree (Implementation Plan).\n1. Start with the 'Goal' or 'Injection' node.\n2. Break down the path into Obstacles and Intermediate Objectives (IO).\n3. **ACTION:** Suggest adding 'Action' nodes and 'IO' nodes in a sequence. Link them to show the path to the goal.",
  "toc:tt:prompt": "Create a Transition Tree (Implementation Plan).\n1. Look for 'Idea' or 'Action' nodes that are not fully connected or implemented.\n2. Break down the steps to achieve them.\n3. Add 'Step' nodes and link them logically (Conditions -> Actions -> Outcomes).",

  "ssm": "You are an expert in Soft Systems Methodology (SSM). Analyze the provided graph model to explore complex, unstructured problems.\nOUTPUT FORMAT:\nReturn a JSON object with two fields:\n1. \"analysis\": A detailed MARKDOWN string explaining your findings using SSM terminology.\n2. \"actions\": An array of suggested graph modifications. Each action must be a function call object: { name: \"addElement\" | \"addRelationship\" | \"deleteElement\" | \"setElementAttribute\", args: { ... } }.",
  "ssm:rich_picture": "Develop elements for a Rich Picture.\n1. Analyze the messy situation. Identify Structures, Processes, Climate, People, and Conflicts.\n2. **ACTION:** Suggest adding nodes for 'Stakeholder', 'Concern', 'Conflict', and 'Environment'. Use expressive relationship labels (e.g., 'fears', 'blocks', 'misunderstands').",
  "ssm:rich_picture:prompt": "Create a 'Rich Picture' of the situation described as: \"{{context}}\".\n1. Identify Stakeholders, Structures, Processes, Climate, and Conflicts.\n2. Suggest nodes for each of these (use 'Actor', 'Process', 'Issue', 'Feeling' tags).\n3. Connect them to show relationships and conflicts (crossed swords).",
  "ssm:catwoe": "Perform a CATWOE Analysis.\n1. Identify Customers, Actors, Transformation, Worldview, Owner, Environment.\n2. **ACTION:** Suggest adding missing nodes to represent these six elements. Ensure the Transformation (Input -> Output) is clearly modeled with nodes.",
  "ssm:catwoe:prompt": "Perform a CATWOE analysis on the current graph.\n1. Identify Customers, Actors, Transformation, Worldview, Owners, Environment.\n2. If any are missing, suggest adding nodes to represent them.\n3. Ensure the Transformation (Input -> T -> Output) is logically connected.",
  "ssm:activity_models": "Design a Conceptual Activity Model.\n1. Based on the Root Definition, determine the minimum necessary activities.\n2. **ACTION:** Suggest adding 'Activity' nodes (verbs) that *must* exist for the system to function. Link them in logical dependencies (A requires B).",
  "ssm:activity_models:prompt": "Based on the Root Definition: \"{{context}}\", build a Conceptual Activity Model.\n1. What activities *must* exist to satisfy this definition?\n2. Add these as 'Activity' nodes.\n3. Link them in a logical dependency order (A enables B).\n4. Add 'Monitor' and 'Control' activities.",
  "ssm:comparison": "Compare the Ideal Activity Model with the Real World graph.\n1. Identify gaps (missing activities) and constraints (real-world blockers).\n2. **ACTION:** Suggest adding 'Gap' nodes where reality differs from the ideal. Suggest 'Accommodation' nodes to resolve these differences culturally or politically.",
  "ssm:comparison:prompt": "Compare the current graph (Real World) with a theoretical ideal Activity Model.\n1. Identify gaps: What necessary activities are missing from the real world graph?\n2. Identify constraints: What real-world nodes are blocking the ideal flow?\n3. Suggest 'Accommodation' nodes to bridge the gap.",

  "swot": "You are a Strategic Analyst. Analyze the provided graph model using the requested framework.\nOUTPUT FORMAT:\nReturn a JSON object with two fields:\n1. \"analysis\": A detailed MARKDOWN string explaining your findings, organized by the categories of the selected framework.\n2. \"actions\": An array of suggested graph modifications. Each action must be a function call object: { name: \"addElement\" | \"addRelationship\" | \"deleteElement\" | \"setElementAttribute\", args: { ... } }.",
  "swot:matrix:prompt": "\n          {{systemPromptBase}}\n          \n          Perform a {{title}} analysis on the provided knowledge graph.\n          {{basePrompt}}\n          {{guidance}}\n          \n          {{focus}}\n\n          Instructions:\n          - Identify key factors based on the graph structure and node attributes.\n          - Return a structured JSON object where keys are the category IDs: {{categoryIds}}.\n          - CRITICAL: Return arrays of STRINGS. Do not return markdown or nested objects in the array items.\n          - Ensure each item is a complete thought/factor.\n          \n          Example JSON format:\n          {\n            \"{{exampleId1}}\": [\"Point 1\", \"Point 2\"],\n            \"{{exampleId2}}\": [\"Point A\", \"Point B\"]\n          }\n          ",
  "swot:matrix": "Perform a comprehensive SWOT Analysis.\n1. Identify internal Strengths and Weaknesses.\n2. Identify external Opportunities and Threats.\n3. Return a structured JSON object with four arrays: \"strengths\", \"weaknesses\", \"opportunities\", \"threats\".\n4. CRITICAL: Each array item must be a single, complete string describing one factor. Do not split sentences into separate items.\n5. Example JSON structure:\n{\n  \"strengths\": [\"Strong brand recognition in US market\", \"Proprietary technology patent\"],\n  \"weaknesses\": [\"High supply chain costs\", \"Limited presence in Asia\"],\n  ...\n}\n6. **ACTION:** Suggest adding nodes tagged 'Strength', 'Weakness', 'Opportunity', 'Threat'.",
  "swot:pestel": "Perform a PESTEL Analysis.\n1. Scan for macro-environmental factors: Political, Economic, Social, Technological, Environmental, Legal.\n2. **ACTION:** Suggest adding nodes for these factors (e.g., \"New Legislation\", \"Inflation\"). Link them to the central organization node with 'affects' or 'constrains'.",
  "swot:steer": "Perform a STEER Analysis (Socio-cultural, Technological, Economic, Ecological, Regulatory).\n1. Analyze these specific external drivers.\n2. **ACTION:** Suggest adding nodes for key trends in these areas. Connect them to the subject to show impact.",
  "swot:destep": "Perform a DESTEP Analysis (Demographic, Economic, Social, Technological, Ecological, Political).\n1. Focus on Demographic shifts in addition to standard PEST factors.\n2. **ACTION:** Suggest adding nodes representing 'Demographic Trend' (e.g., \"Aging Population\"). Link to market/service nodes.",
  "swot:longpest": "Perform a LoNGPEST Analysis (Local, National, Global PEST).\n1. Analyze factors at different geographic scales.\n2. **ACTION:** Suggest adding PEST nodes with attributes {Scale=\"Local\" | \"National\" | \"Global\"}. Ensure global trends and local realities are represented.",
  "swot:five_forces": "Analyze Porter’s Five Forces.\n1. Assess: Supplier Power, Buyer Power, Competitive Rivalry, Threat of Substitution, Threat of New Entry.\n2. **ACTION:** Suggest adding nodes for 'Competitor', 'Supplier', 'Buyer', 'Substitute', 'Entrant'. Link them to the central node (e.g., \"Supplier -> exercises power over -> Company\").",
  "swot:cage": "Apply the CAGE Distance Framework.\n1. Analyze Cultural, Administrative, Geographic, and Economic distances between two markets/countries.\n2. **ACTION:** Suggest adding 'Distance' nodes (e.g., \"Language Difference\", \"Trade Tariff\", \"Physical Distance\"). Link the two market nodes with these distance factors.",

  "swot_base:matrix": "Perform a SWOT Analysis. Identify internal Strengths and Weaknesses, and external Opportunities and Threats.",
  "swot_base:five_forces": "Analyze Porter's Five Forces. Identify specific factors for each force based on the graph context.",
  "swot_base:pestel": "Perform a PESTEL Analysis. Identify Political, Economic, Social, Technological, Environmental, and Legal factors affecting the subject.",
  "swot_base:steer": "Perform a STEER Analysis. Identify specific factors for each category based on the graph context.",
  "swot_base:destep": "Perform a DESTEP Analysis. Identify specific factors for each category based on the graph context.",
  "swot_base:longpest": "Perform a LoNGPEST Analysis. Identify PEST factors at Local, National, and Global levels based on the graph context.",
  "swot_base:cage": "Perform a CAGE Distance Analysis. Identify specific distance factors between the entities/markets in the graph.",

  "transform:linguistic": "You are a linguistic expert. Transform the following list of words/phrases into {{mode}}.\n\nWords: {{words}}\n\nReturn a JSON object containing an array of mappings.\nStructure: { \"mappings\": [ { \"original\": \"word\", \"transformed\": \"new_word\" }, ... ] }\n\n- Keep the casing consistent.\n- If a word cannot be transformed meaningfully, keep it as is.\n- \"Related\": contextually associated concepts.\n- \"Metaphors\": figurative representations.\n- \"Hypernyms\": more general categories.\n- \"Hyponyms\": more specific examples.\n\nOutput valid JSON only.",
  
  "mermaid:flowchart": "Provide mermaid markdown for a flowchart for this",
  "mermaid:mindmap": "Provide mermaid markdown for a mind map for this",
  "mermaid:usecase": "Provide mermaid markdown for a use case diagram based on a left to right flowchart diagram that uses stadium-shaped nodes by wrapping the node names in round and square brackets ([node name]) for this",
  "mermaid:decomposition": "Provide mermaid markdown for a functional decomposition diagram showing functions as boxes. Sub-functions of each function should be shown as subgraphs in their own boxes inside the box for the function they belong to for this",
  "mermaid:sequence": "Provide mermaid markdown for a sequence diagram for this",
  "mermaid:class": "Provide mermaid markdown for a class diagram for this",
  "mermaid:perimeter": "Provide mermaid markdown for a perimeter diagram showing the perimeter as a box with a dashed line and the components of the system inside connected via firewall to systems outside the perimeter for this",
  "mermaid:er": "Provide mermaid markdown for an entity relationship diagram for this",
  "mermaid:state": "Provide mermaid markdown for a state diagram for this",
  "mermaid:timeline": "Provide mermaid markdown for a timeline for this",
  "mermaid:gantt": "Provide mermaid markdown for a Gantt chart breaking it down into phases as appropriate for this"
};
